# Generated by Django 5.0.2 on 2024-03-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_ownership_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacture_location',
            field=models.CharField(choices=[('Abu Dhabi', 'Abu Dhabi'), ('Dubai', 'Dubai'), ('Ajman', 'Ajman')], default='Abu Dhabi', max_length=50, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_ownership',
            field=models.CharField(choices=[('SL', 'Seller'), ('US', 'Final User'), ('US', 'user'), ('MF', 'Manufacturer'), ('MC', 'Merchant')], default='US', max_length=50, verbose_name='Ownership'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_catagory',
            field=models.CharField(choices=[('SL', 'Seller'), ('US', 'Final User'), ('US', 'user'), ('MF', 'Manufacturer'), ('MC', 'Merchant')], default='US', max_length=2, verbose_name='Catagory'),
        ),
    ]
