# Generated by Django 5.0.2 on 2024-03-21 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_product_manufacture_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50, verbose_name='Event Name')),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
                ('event_location', models.CharField(max_length=50, verbose_name='Location')),
                ('event_description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='manufacture_location',
            field=models.CharField(choices=[('AD', 'Abu Dhabi'), ('DU', 'Dubai'), ('AJ', 'Ajman'), ('SH', 'Sharjah'), ('AL', 'Al Ain'), ('FU', 'Fujairah'), ('RA', 'Ras Al Khaimah'), ('UM', 'Umm Al Quwain'), ('OT', 'Other')], default='Abu Dhabi', max_length=50, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacture_location',
            field=models.CharField(choices=[('AD', 'Abu Dhabi'), ('DU', 'Dubai'), ('AJ', 'Ajman'), ('SH', 'Sharjah'), ('AL', 'Al Ain'), ('FU', 'Fujairah'), ('RA', 'Ras Al Khaimah'), ('UM', 'Umm Al Quwain'), ('OT', 'Other')], default='AD', max_length=50, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer_name',
            field=models.CharField(max_length=50, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_mf_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Manufacturing Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=50, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_ownership',
            field=models.CharField(choices=[('CS', 'Consumer'), ('MF', 'New Product'), ('MC', 'Merchant')], default='CS', max_length=50, verbose_name='Ownership'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_catagory',
            field=models.CharField(choices=[('CS', 'Consumer'), ('MF', 'New Product'), ('MC', 'Merchant')], default='US', max_length=2, verbose_name='Catagory'),
        ),
    ]
