# Generated by Django 5.0.2 on 2024-03-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_ownership_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuseproducts',
            name='product_condition',
            field=models.CharField(choices=[('G', 'Good'), ('B', 'Bad'), ('E', 'Excellent'), ('N', 'New'), ('U', 'Used'), ('R', 'Refurbished'), ('D', 'Damaged'), ('W', 'Worn'), ('S', 'Scratched'), ('C', 'Cracked'), ('P', 'Patched'), ('F', 'Faded')], default='Good', max_length=50, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='reuseproducts',
            name='product_description',
            field=models.TextField(max_length=100, verbose_name='Description'),
        ),
    ]
