# Generated by Django 5.0.2 on 2024-03-30 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_reuseproducts_product_price_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('locality', models.CharField(max_length=50, verbose_name='Locality')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('zipcode', models.IntegerField(verbose_name='Zip Code')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('reg_date', models.DateField(verbose_name='Registration Date')),
                ('phone', models.IntegerField(verbose_name='Phone Number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
