# Generated by Django 5.0.2 on 2024-03-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, verbose_name="Product title"),
                ),
                ("selling_price", models.FloatField(verbose_name="Price")),
                ("discounted_price", models.FloatField(verbose_name="Discount")),
                (
                    "description",
                    models.TextField(default="", verbose_name="Description"),
                ),
                ("prodapp", models.TextField(default="", verbose_name="I don't know")),
                (
                    "catagory",
                    models.CharField(
                        choices=[("RC", "Recycable"), ("NR", "Non Recycable")],
                        max_length=2,
                        verbose_name="Catagories",
                    ),
                ),
                (
                    "product_img",
                    models.ImageField(upload_to="product", verbose_name="Images"),
                ),
            ],
        ),
    ]
