# Generated by Django 5.0.2 on 2024-04-03 21:48

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50, verbose_name='Event Name')),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
                ('event_location', models.CharField(max_length=50, verbose_name='Location')),
                ('event_description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('locality', models.CharField(max_length=50, verbose_name='Locality')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('zipcode', models.IntegerField(verbose_name='Zip Code')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('reg_date', models.DateField(verbose_name='Registration Date')),
                ('phone', models.IntegerField(verbose_name='Phone Number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone')),
                ('full_name', models.CharField(default='', max_length=50, verbose_name='Full Name')),
                ('city', models.CharField(choices=[('AD', 'Abu Dhabi'), ('DU', 'Dubai'), ('AJ', 'Ajman'), ('SH', 'Sharjah'), ('AL', 'Al Ain'), ('FU', 'Fujairah'), ('RA', 'Ras Al Khaimah'), ('UM', 'Umm Al Quwain')], default='AD', max_length=50, verbose_name='City')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('country_origin', models.CharField(choices=[('UAE', 'United Arab Emirates'), ('USA', 'United States of America'), ('UK', 'United Kingdom'), ('IND', 'India'), ('CHN', 'China'), ('UG', 'Uganda')], default='UAE', max_length=50, verbose_name='Country Origin')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('email', models.EmailField(default='', max_length=20, verbose_name='email')),
                ('user_type', models.CharField(choices=[('CS', 'Consumer'), ('MC', 'Merchant')], default='CS', max_length=50, verbose_name='User Type')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=30, verbose_name='Unique Number')),
                ('product_name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('manufacturer_name', models.CharField(max_length=50, verbose_name='Company Name')),
                ('manufacture_location', models.CharField(choices=[('AD', 'Abu Dhabi'), ('DU', 'Dubai'), ('AJ', 'Ajman'), ('SH', 'Sharjah'), ('AL', 'Al Ain'), ('FU', 'Fujairah'), ('RA', 'Ras Al Khaimah'), ('UM', 'Umm Al Quwain')], default='AD', max_length=50, verbose_name='Location')),
                ('product_type', models.CharField(choices=[('RC', 'Recycable'), ('NRC', 'Non Recycable'), ('RU', 'Reusable'), ('RCV', 'Recover')], default='RC', max_length=50, verbose_name='Product Type')),
                ('product_quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('product_mf_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Manufacturing Date')),
                ('product_expiry_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Expiry Date')),
                ('product_pdf', models.FileField(blank=True, upload_to='Added_Products/pdf_files', verbose_name='PDF QR Code')),
                ('product_qr_code', models.ImageField(upload_to='Added_Products/Qr_codes', verbose_name='QR Codes')),
                ('product_ownership', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.profileuser', verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RC', 'Recycaled'), ('RU', 'Reusing'), ('RCV', 'Recover'), ('NO', 'Not Recyled')], default='NO', max_length=10, verbose_name='Recycle Status')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('product_quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('action', models.CharField(default=' ', max_length=50, verbose_name='Action')),
                ('product_uid', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Product Id')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('product', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='who_own_the_product', to='myapp.product', verbose_name='Product')),
                ('new_owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.profileuser', verbose_name='New Owner')),
            ],
        ),
        migrations.CreateModel(
            name='ReuseProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('product', models.CharField(max_length=50, verbose_name='Product')),
                ('product_quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('product_catagories', models.CharField(choices=[('RC', 'Recycable'), ('NRC', 'Non Recycable'), ('RU', 'Reusable'), ('RCV', 'Recover')], default='RU', max_length=3, verbose_name='Catagories')),
                ('product_description', models.TextField(max_length=100, verbose_name='Description')),
                ('product_condition', models.CharField(choices=[('G', 'Good'), ('B', 'Bad'), ('E', 'Excellent'), ('N', 'New'), ('U', 'Used'), ('R', 'Refurbished'), ('D', 'Damaged'), ('W', 'Worn'), ('S', 'Scratched'), ('C', 'Cracked'), ('P', 'Patched'), ('F', 'Faded')], default='Good', max_length=50, verbose_name='Condition')),
                ('product_image', models.ImageField(upload_to='product_images/', verbose_name='Image')),
                ('product_address', models.TextField(max_length=50, verbose_name='Address')),
                ('product_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.reuseproducts', verbose_name='Product')),
            ],
        ),
    ]
