# Generated by Django 5.0.4 on 2024-04-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileuser",
            name="recover_rewards",
            field=models.IntegerField(default=0, verbose_name="Recover Rewards"),
        ),
        migrations.AddField(
            model_name="profileuser",
            name="recycle_rewards",
            field=models.IntegerField(default=0, verbose_name="Recycle Rewards"),
        ),
        migrations.AddField(
            model_name="profileuser",
            name="reduce_rewards",
            field=models.IntegerField(default=0, verbose_name="Reduce Rewards"),
        ),
        migrations.AddField(
            model_name="profileuser",
            name="reuse_rewards",
            field=models.IntegerField(default=0, verbose_name="Reuse Rewards"),
        ),
        migrations.AddField(
            model_name="profileuser",
            name="reward_points_total",
            field=models.IntegerField(default=0, verbose_name="Reward Points"),
        ),
    ]
