# Generated by Django 5.0.4 on 2024-04-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_remove_profileuser_reward_points_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileuser",
            name="recover_rewards",
            field=models.IntegerField(default=50, verbose_name="Recover Rewards"),
        ),
        migrations.AlterField(
            model_name="profileuser",
            name="recycle_rewards",
            field=models.IntegerField(default=50, verbose_name="Recycle Rewards"),
        ),
        migrations.AlterField(
            model_name="profileuser",
            name="reduce_rewards",
            field=models.IntegerField(default=50, verbose_name="Reduce Rewards"),
        ),
        migrations.AlterField(
            model_name="profileuser",
            name="reuse_rewards",
            field=models.IntegerField(default=50, verbose_name="Reuse Rewards"),
        ),
    ]
