# Generated by Django 5.0.4 on 2024-04-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_profileuser_recover_rewards_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                upload_to="profile_pictures/",
                verbose_name="Profile Picture",
            ),
        ),
        migrations.AlterField(
            model_name="profileuser",
            name="phone",
            field=models.CharField(max_length=15, verbose_name="Phone"),
        ),
    ]
