# Generated by Django 5.0.3 on 2024-03-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_profileuser_full_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileuser",
            name="email",
            field=models.EmailField(default="", max_length=20, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="profileuser",
            name="phone",
            field=models.CharField(max_length=10, verbose_name="Phone"),
        ),
    ]
