# Generated by Django 5.0.2 on 2024-03-29 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_profileuser_email_alter_profileuser_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownership',
            name='product',
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='country_origin',
            field=models.CharField(choices=[('UAE', 'United Arab Emirates'), ('USA', 'United States of America'), ('UK', 'United Kingdom'), ('IND', 'India'), ('CHN', 'China'), ('UG', 'Uganda')], default='UAE', max_length=50, verbose_name='Country Origin'),
        ),
        migrations.CreateModel(
            name='ReuseProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('product', models.CharField(max_length=50, verbose_name='Product')),
                ('product_quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('product_catagories', models.CharField(choices=[('RC', 'Recycable'), ('NRC', 'Non Recycable'), ('RU', 'Reusable'), ('RCV', 'Recover')], default='RU', max_length=3, verbose_name='Catagories')),
                ('product_description', models.TextField(verbose_name='Description')),
                ('product_condition', models.CharField(choices=[('RC', 'Recycable'), ('NRC', 'Non Recycable'), ('RU', 'Reusable'), ('RCV', 'Recover')], default='Good', max_length=50, verbose_name='Condition')),
                ('product_image', models.ImageField(upload_to='product_images/', verbose_name='Image')),
                ('product_address', models.TextField(max_length=50, verbose_name='Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='ownership',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='who_own_the_product', to='myapp.product', verbose_name='Product'),
        ),
    ]
