# Generated by Django 5.0.2 on 2024-03-02 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_alter_question_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 2, 16, 6, 0, 716399, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date Published",
            ),
        ),
    ]
