# Generated by Django 5.0.2 on 2024-03-09 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_id",
                    models.CharField(max_length=50, verbose_name="Product ID"),
                ),
                (
                    "product_quantity",
                    models.IntegerField(verbose_name="Product Quantity"),
                ),
                (
                    "product_name",
                    models.CharField(max_length=15, verbose_name="Product Name"),
                ),
                (
                    "product_manufacture_date",
                    models.DateTimeField(verbose_name="Date of Manufacture"),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[("RC", "Recycable"), ("NRC", "Non Recycable")],
                        max_length=50,
                        verbose_name="Product Type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manufacturer_name",
                    models.CharField(
                        default="Unknown", max_length=50, verbose_name="Name"
                    ),
                ),
                (
                    "manufacture_location",
                    models.CharField(
                        choices=[
                            ("Abu Dhabi", "Abu Dhabi"),
                            ("Dubai", "Dubai"),
                            ("Ajman", "Ajman"),
                        ],
                        default="Abu Dhabi",
                        max_length=50,
                        verbose_name="Location",
                    ),
                ),
                (
                    "products_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.products",
                        verbose_name="Products details",
                    ),
                ),
            ],
        ),
    ]
