# Generated by Django 5.0.2 on 2024-03-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturer",
            name="product_quantity",
            field=models.IntegerField(default=0, verbose_name="Quantity"),
        ),
    ]
