# Generated by Django 5.0.2 on 2024-03-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_rename_products_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_ownership",
            field=models.CharField(
                choices=[("MC", "Merchant"), ("CN", "Consumer"), ("US", "User")],
                default="US",
                max_length=50,
                verbose_name="Ownership",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_id",
            field=models.CharField(
                editable=False, max_length=50, unique=True, verbose_name="Product ID"
            ),
        ),
    ]
