# Generated by Django 5.0.3 on 2024-03-24 06:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_product_product_ownership_alter_product_product_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AddEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(max_length=50, verbose_name="Event Name"),
                ),
                ("event_date", models.DateTimeField(verbose_name="Event Date")),
                (
                    "event_location",
                    models.CharField(max_length=50, verbose_name="Location"),
                ),
                (
                    "event_description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Last Name"),
                ),
                (
                    "user_name",
                    models.CharField(max_length=50, verbose_name="User Name"),
                ),
                (
                    "telephone_number",
                    models.CharField(max_length=10, verbose_name="Telephone"),
                ),
                (
                    "user_email",
                    models.EmailField(max_length=254, verbose_name="Email Id"),
                ),
                (
                    "user_catagory",
                    models.CharField(
                        choices=[
                            ("CS", "Consumer"),
                            ("MF", "New Product"),
                            ("MC", "Merchant"),
                        ],
                        default="US",
                        max_length=2,
                        verbose_name="Catagory",
                    ),
                ),
                ("user_points", models.IntegerField(default=0, verbose_name="Points")),
                (
                    "product_quantity",
                    models.IntegerField(default=0, verbose_name="Quantity"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="manufacturer",
            name="product_expiry_date",
        ),
        migrations.RemoveField(
            model_name="manufacturer",
            name="product_mf_date",
        ),
        migrations.RemoveField(
            model_name="manufacturer",
            name="product_type",
        ),
        migrations.RemoveField(
            model_name="product",
            name="manufacturer",
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="manufacturer_address",
            field=models.CharField(
                default="Abu Dhabi", max_length=50, verbose_name="Address"
            ),
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="manufacturer_email",
            field=models.EmailField(default="", max_length=50, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="manufacturer_phone",
            field=models.CharField(default="", max_length=50, verbose_name="Phone"),
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="product_catgories",
            field=models.CharField(
                choices=[
                    ("RC", "Recycable"),
                    ("NRC", "Non Recycable"),
                    ("RU", "Reusable"),
                    ("RCV", "Recover"),
                ],
                default="RC",
                max_length=3,
                verbose_name="Catagories",
            ),
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="product_description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="manufacture_location",
            field=models.CharField(
                choices=[
                    ("AD", "Abu Dhabi"),
                    ("DU", "Dubai"),
                    ("AJ", "Ajman"),
                    ("SH", "Sharjah"),
                    ("AL", "Al Ain"),
                    ("FU", "Fujairah"),
                    ("RA", "Ras Al Khaimah"),
                    ("UM", "Umm Al Quwain"),
                    ("OT", "Other"),
                ],
                default="Abu Dhabi",
                max_length=50,
                verbose_name="Location",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="manufacturer_name",
            field=models.CharField(max_length=50, verbose_name="Company Name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="manufacture_location",
            field=models.CharField(
                choices=[
                    ("AD", "Abu Dhabi"),
                    ("DU", "Dubai"),
                    ("AJ", "Ajman"),
                    ("SH", "Sharjah"),
                    ("AL", "Al Ain"),
                    ("FU", "Fujairah"),
                    ("RA", "Ras Al Khaimah"),
                    ("UM", "Umm Al Quwain"),
                    ("OT", "Other"),
                ],
                default="AD",
                max_length=50,
                verbose_name="Location",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="manufacturer_name",
            field=models.CharField(max_length=50, verbose_name="Company Name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_mf_date",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Manufacturing Date"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(max_length=50, verbose_name="Product Name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_ownership",
            field=models.CharField(
                choices=[("CS", "Consumer"), ("MF", "New Product"), ("MC", "Merchant")],
                default="CS",
                max_length=50,
                verbose_name="Ownership",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="Quantity"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("RC", "Recycable"),
                    ("NRC", "Non Recycable"),
                    ("RU", "Reusable"),
                    ("RCV", "Recover"),
                ],
                default="RC",
                max_length=50,
                verbose_name="Product Type",
            ),
        ),
        migrations.CreateModel(
            name="Ownership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RC", "Recycaled"),
                            ("RU", "Reusing"),
                            ("RCV", "Recover"),
                            ("NO", "Not Recyled"),
                        ],
                        default="NO",
                        max_length=10,
                        verbose_name="Recycle Status",
                    ),
                ),
                ("date", models.DateTimeField(auto_now=True, verbose_name="Date")),
                (
                    "product_quantity",
                    models.IntegerField(default=0, verbose_name="Quantity"),
                ),
                (
                    "product",
                    models.ManyToManyField(
                        related_name="who_own_the_product",
                        to="myapp.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
    ]
